services:
  - type: web
    name: customisable-chatbot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MODEL_NAME
        value: gemini-1.5-flash
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: vector_stores
      - key: MAX_CONTENT_LENGTH
        value: 104857600
